# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/joel/Projects/markovcpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/joel/Projects/markovcpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/joel/Projects/markovcpp/CMakeFiles /home/joel/Projects/markovcpp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/joel/Projects/markovcpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named markov.exe

# Build rule for target.
markov.exe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 markov.exe
.PHONY : markov.exe

# fast build rule for target.
markov.exe/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/markov.exe.dir/build.make CMakeFiles/markov.exe.dir/build
.PHONY : markov.exe/fast

#=============================================================================
# Target rules for targets named tinyxml2

# Build rule for target.
tinyxml2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tinyxml2
.PHONY : tinyxml2

# fast build rule for target.
tinyxml2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyxml2.dir/build.make CMakeFiles/tinyxml2.dir/build
.PHONY : tinyxml2/fast

include/tinyxml2.o: include/tinyxml2.cpp.o

.PHONY : include/tinyxml2.o

# target to build an object file
include/tinyxml2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyxml2.dir/build.make CMakeFiles/tinyxml2.dir/include/tinyxml2.cpp.o
.PHONY : include/tinyxml2.cpp.o

include/tinyxml2.i: include/tinyxml2.cpp.i

.PHONY : include/tinyxml2.i

# target to preprocess a source file
include/tinyxml2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyxml2.dir/build.make CMakeFiles/tinyxml2.dir/include/tinyxml2.cpp.i
.PHONY : include/tinyxml2.cpp.i

include/tinyxml2.s: include/tinyxml2.cpp.s

.PHONY : include/tinyxml2.s

# target to generate assembly for a file
include/tinyxml2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyxml2.dir/build.make CMakeFiles/tinyxml2.dir/include/tinyxml2.cpp.s
.PHONY : include/tinyxml2.cpp.s

markov.o: markov.cpp.o

.PHONY : markov.o

# target to build an object file
markov.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/markov.exe.dir/build.make CMakeFiles/markov.exe.dir/markov.cpp.o
.PHONY : markov.cpp.o

markov.i: markov.cpp.i

.PHONY : markov.i

# target to preprocess a source file
markov.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/markov.exe.dir/build.make CMakeFiles/markov.exe.dir/markov.cpp.i
.PHONY : markov.cpp.i

markov.s: markov.cpp.s

.PHONY : markov.s

# target to generate assembly for a file
markov.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/markov.exe.dir/build.make CMakeFiles/markov.exe.dir/markov.cpp.s
.PHONY : markov.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... markov.exe"
	@echo "... tinyxml2"
	@echo "... include/tinyxml2.o"
	@echo "... include/tinyxml2.i"
	@echo "... include/tinyxml2.s"
	@echo "... markov.o"
	@echo "... markov.i"
	@echo "... markov.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

